name: build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup JBang
      uses: jbangdev/setup-jbang@main

    - name: Install jq
      run: sudo apt-get install jq

    - name: Run JBang Builds
      run: .github/test.sh

